fix spelling mistakes, fix broken link
mltframework/shotcut_web pull request #2
Opened 2018-09-23 20:13 UTC by realsobek

for siteindex.html: I hope the solution to fix the link is OK

2018-09-23 21:26 UTC, ddennedy requested changes

2018-09-23 21:26 UTC, ddennedy commented on download.md
> -from the store with `snap install shotcut --classic`
Thank you for the help. The two trailing spaces at the end of this line are significant. They introduce a line break.

2018-09-23 21:26 UTC, ddennedy commented on siteindex.html
> +      <a href="{{ site.baseurl }}../blog/">News (Blog)</a><br>
This should be "{{ site.baseurl }}/blog/"

2018-09-24 21:03 UTC, realsobek commented
thank you for feedback and explanation; the changes have been incorporated

2018-09-25 00:45 UTC, ddennedy approved these changes

2018-09-25 00:45 UTC, merged

2018-09-25 00:57 UTC, ddennedy commented
Thank you. These changes are live now.